//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterTwitter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterTwitter.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_add_photo.png.
        /// </summary>
        public static string AddPhotoIcon {
            get {
                return ResourceManager.GetString("AddPhotoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile in BlackList.
        /// </summary>
        public static string BlacklistText {
            get {
                return ResourceManager.GetString("BlacklistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string BookmarksTitle {
            get {
                return ResourceManager.GetString("BookmarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need allow to use camera on your device.
        /// </summary>
        public static string CameraPermisionWarning {
            get {
                return ResourceManager.GetString("CameraPermisionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change profile.
        /// </summary>
        public static string ChangeProfileLable {
            get {
                return ResourceManager.GetString("ChangeProfileLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_clear.png.
        /// </summary>
        public static string ClearImage {
            get {
                return ResourceManager.GetString("ClearImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not match.
        /// </summary>
        public static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        public static string CreateAccountLabel {
            get {
                return ResourceManager.GetString("CreateAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all bookmarks.
        /// </summary>
        public static string DeleteBookmarksText {
            get {
                return ResourceManager.GetString("DeleteBookmarksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email.
        /// </summary>
        public static string EmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields shoudn&apos;t be empty.
        /// </summary>
        public static string EmptyEntryText {
            get {
                return ResourceManager.GetString("EmptyEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already exist!.
        /// </summary>
        public static string ExistEmailError {
            get {
                return ResourceManager.GetString("ExistEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_eye_off.png.
        /// </summary>
        public static string EyeOffImage {
            get {
                return ResourceManager.GetString("EyeOffImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_eye_on.png.
        /// </summary>
        public static string EyeOnImage {
            get {
                return ResourceManager.GetString("EyeOnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your account.
        /// </summary>
        public static string GetAccountLabel {
            get {
                return ResourceManager.GetString("GetAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user data.
        /// </summary>
        public static string InvalidUserDataText {
            get {
                return ResourceManager.GetString("InvalidUserDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_left_grey.png.
        /// </summary>
        public static string LeftGreyImage {
            get {
                return ResourceManager.GetString("LeftGreyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_left.png.
        /// </summary>
        public static string LeftImage {
            get {
                return ResourceManager.GetString("LeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked your post.
        /// </summary>
        public static string LikedPostText {
            get {
                return ResourceManager.GetString("LikedPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string LikesText {
            get {
                return ResourceManager.GetString("LikesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pic_logo_small.png.
        /// </summary>
        public static string LogoImage {
            get {
                return ResourceManager.GetString("LogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        public static string MutedText {
            get {
                return ResourceManager.GetString("MutedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute profiles.
        /// </summary>
        public static string MuteProfilesText {
            get {
                return ResourceManager.GetString("MuteProfilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string MuteText {
            get {
                return ResourceManager.GetString("MuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameEntryPlaceHolder {
            get {
                return ResourceManager.GetString("NameEntryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type your name.
        /// </summary>
        public static string NameErrorMessage {
            get {
                return ResourceManager.GetString("NameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll need a password.
        /// </summary>
        public static string NeedPasswordLabel {
            get {
                return ResourceManager.GetString("NeedPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPasswordText {
            get {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        public static string NoInternetText {
            get {
                return ResourceManager.GetString("NoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationPageTitle {
            get {
                return ResourceManager.GetString("NotificationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPasswordText {
            get {
                return ResourceManager.GetString("OldPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too short or contains whitespace.
        /// </summary>
        public static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pic_profile_header_photo.jpg.
        /// </summary>
        public static string PicProfileHeaderImage {
            get {
                return ResourceManager.GetString("PicProfileHeaderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string PostsText {
            get {
                return ResourceManager.GetString("PostsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile in BlackList.
        /// </summary>
        public static string ProfileInBlackListText {
            get {
                return ResourceManager.GetString("ProfileInBlackListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong.
        /// </summary>
        public static string RandomError {
            get {
                return ResourceManager.GetString("RandomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_right.png.
        /// </summary>
        public static string RightImage {
            get {
                return ResourceManager.GetString("RightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved your post.
        /// </summary>
        public static string SavedPostText {
            get {
                return ResourceManager.GetString("SavedPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ic_check_blue.png.
        /// </summary>
        public static string SaveIcon {
            get {
                return ResourceManager.GetString("SaveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareLabelText {
            get {
                return ResourceManager.GetString("ShareLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take picture from camera.
        /// </summary>
        public static string TakeCameraPicture {
            get {
                return ResourceManager.GetString("TakeCameraPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take picture from gallery.
        /// </summary>
        public static string TakeGalleryPicture {
            get {
                return ResourceManager.GetString("TakeGalleryPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VideoText {
            get {
                return ResourceManager.GetString("VideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email or password.
        /// </summary>
        public static string WrongEmailPasswordText {
            get {
                return ResourceManager.GetString("WrongEmailPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wron user&apos;s name.
        /// </summary>
        public static string WrongNameText {
            get {
                return ResourceManager.GetString("WrongNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered wrong old password.
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
    }
}
