//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterTwitter.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("InterTwitter.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddPhotoIcon {
            get {
                return ResourceManager.GetString("AddPhotoIcon", resourceCulture);
            }
        }
        
        public static string CameraPermisionWarning {
            get {
                return ResourceManager.GetString("CameraPermisionWarning", resourceCulture);
            }
        }
        
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        public static string ChangeProfileLable {
            get {
                return ResourceManager.GetString("ChangeProfileLable", resourceCulture);
            }
        }
        
        public static string ClearImage {
            get {
                return ResourceManager.GetString("ClearImage", resourceCulture);
            }
        }
        
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        public static string CreateAccountLabel {
            get {
                return ResourceManager.GetString("CreateAccountLabel", resourceCulture);
            }
        }
        
        public static string EmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailErrorMessage", resourceCulture);
            }
        }
        
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        public static string EmptyEntryText {
            get {
                return ResourceManager.GetString("EmptyEntryText", resourceCulture);
            }
        }
        
        public static string EyeOffImage {
            get {
                return ResourceManager.GetString("EyeOffImage", resourceCulture);
            }
        }
        
        public static string EyeOnImage {
            get {
                return ResourceManager.GetString("EyeOnImage", resourceCulture);
            }
        }
        
        public static string GetAccountLabel {
            get {
                return ResourceManager.GetString("GetAccountLabel", resourceCulture);
            }
        }
        
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        public static string InvalidUserDataText {
            get {
                return ResourceManager.GetString("InvalidUserDataText", resourceCulture);
            }
        }
        
        public static string LeftImage {
            get {
                return ResourceManager.GetString("LeftImage", resourceCulture);
            }
        }
        
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        public static string LogoImage {
            get {
                return ResourceManager.GetString("LogoImage", resourceCulture);
            }
        }
        
        public static string LogOutError {
            get {
                return ResourceManager.GetString("LogOutError", resourceCulture);
            }
        }
        
        public static string NameEntryPlaceHolder {
            get {
                return ResourceManager.GetString("NameEntryPlaceHolder", resourceCulture);
            }
        }
        
        public static string NameErrorMessage {
            get {
                return ResourceManager.GetString("NameErrorMessage", resourceCulture);
            }
        }
        
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        public static string NeedPasswordLabel {
            get {
                return ResourceManager.GetString("NeedPasswordLabel", resourceCulture);
            }
        }
        
        public static string NewPasswordText {
            get {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }
        
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        public static string NoInternetText {
            get {
                return ResourceManager.GetString("NoInternetText", resourceCulture);
            }
        }
        
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        public static string OldPasswordText {
            get {
                return ResourceManager.GetString("OldPasswordText", resourceCulture);
            }
        }
        
        public static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        public static string PicProfileHeaderImage {
            get {
                return ResourceManager.GetString("PicProfileHeaderImage", resourceCulture);
            }
        }
        
        public static string SaveIcon {
            get {
                return ResourceManager.GetString("SaveIcon", resourceCulture);
            }
        }
        
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        public static string TakeCameraPicture {
            get {
                return ResourceManager.GetString("TakeCameraPicture", resourceCulture);
            }
        }
        
        public static string TakeGalleryPicture {
            get {
                return ResourceManager.GetString("TakeGalleryPicture", resourceCulture);
            }
        }
        
        public static string WrongEmailPasswordText {
            get {
                return ResourceManager.GetString("WrongEmailPasswordText", resourceCulture);
            }
        }
        
        public static string WrongNameText {
            get {
                return ResourceManager.GetString("WrongNameText", resourceCulture);
            }
        }
        
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
    }
}
